### PR TITLE
ru-translation-done

### PR DESCRIPTION
**Pull request by TombOfVARN**
Done. I didn't use any special symbols. Let me know later if you need my help with line breaks.
Resulting translation took into consideration both MM7 and MM8 variants. I did my best to improve upon it and not make it worse.
You can change **any dot** into \n. Much alike original EN file.
Also, let me know when I can try russian version myself :)
If I can have one request, please allow for the game to be played faster, I am used to rapid-fire decisions of original game, this version feels very slow.

### CODE REVIEW

**Comment by TombOfVARN** [comment]
Also, cards like "Barracks" may have their text too long. Need to review ingame.

**Comment by tomchen** [comment]
Translation done

The original game is actually pretty slow if you compare it to ArcoMage HD. I'm wondering which browser you play ArcoMage HD with, it works best in Google Chrome (and Chrome engine-based browsers), it may have performance issue if you play it in Safari or Firefox, but it all depends on your CPU/GPU. However there are indeed some delay constants in ArcoMage HD's source code I can reduce, to speed it up further, and I have just done that.

The text length, yeah, I will see how to adjust the font size to fit

**Comment by TombOfVARN** [comment]
I'm using Firefox, it's my fav browser. Welp, I guess it's browser-related then.

**Comment by TombOfVARN** [comment]
I guess the card with longest text is Barracks. I may be able to shorten certain card texts if needed. I went for the compromise of it being readable and correct, but it may be possible to crop a few symbols here and there, if necessary.

**Comment by tomchen** [comment]
I added some new strings and machine translated them.

https://github.com/arcomage/arcomage-hd/blob/0ee731ba2a1d62000a60ae4e7683533efedbb47a/src/i18n/main/ru.ts#L6-L28

Have a look and correct them (if needed) please.

**Comment by tomchen** [comment]
And `(including an informative tutorial image in English)` here

https://github.com/arcomage/arcomage-hd/blob/a565115459ee2c50b62cac1316f59b52393bec9f/src/i18n/main/ru.ts#L65-L71

**Comment by tomchen** [comment]
I'm coding the multiplayer feature, the code is not in the `main` branch but [`multiplayer` branch](https://github.com/arcomage/arcomage-hd/tree/multiplayer). I'll merge it into `main` once it's done.

Here are the recently added, multiplayer-related strings to be translated or reviewed:

https://github.com/arcomage/arcomage-hd/blob/a8d8dfa3cdd4a10e39e509ae6a180df171468ed2/src/i18n/main/ru.ts#L50-L72

**Pull request closed without merging**
